import { ListItem } from '../common/update'

export const items: ListItem[] = [
  {
    time: '00:00',
    page: 1,
    title: '关于华灯宴的传说·其一',
  },
  {
    time: '01:03',
    page: 1,
    title: '开幕「宴平乐」',
    type: '音乐·PV',
  },
  {
    time: '05:29',
    page: 1,
    title: '主持 1 - 灵梦, 文',
  },
  {
    time: '07:41',
    page: 1,
    title: '神之乐章 - 幻想乡世界之旅',
    type: 'MAD',
    aid: '338802856',
    bvid: 'BV1QR4y1j7ry',
  },
  {
    time: '10:26',
    page: 1,
    title: '熙攘市场何处在 ~ Immemorial Otomads',
    type: '音MAD',
    aid: '723815423',
    bvid: 'BV1mS4y1k77g',
  },
  {
    time: '18:28',
    page: 1,
    title: '秘封二人的秘密',
    type: '手书',
  },
  {
    time: '23:36',
    page: 1,
    title: '爱丽丝梦游仙境',
    type: '音乐剧',
  },
  {
    time: '32:52',
    page: 1,
    title: '东喜发财',
    type: '音乐·手书',
  },
  {
    time: '35:54',
    page: 1,
    title: '主持 2 - 阿求, 妖梦',
  },
  {
    time: '37:03',
    page: 1,
    title: '你是袿姬',
    type: '相声',
    aid: '978787163',
    bvid: 'BV1t44y1W7EM',
  },
  {
    time: '49:52',
    page: 1,
    title: '为你心里小鹿乱撞',
    type: '动画',
    aid: '766284445',
    bvid: 'BV1Gr4y1h7Md',
  },
  {
    time: '54:31',
    page: 1,
    title: '东方偶像是传奇 重新开始',
    type: 'MMD',
  },
  {
    time: '56:57',
    page: 1,
    title: '彼与此之乡',
    type: '绘画',
    aid: '766277013',
    bvid: 'BV1fr4y187vm',
  },
  {
    time: '60:47',
    page: 1,
    title: '无法逾越的一寸之壁',
    type: '3D',
  },
  {
    time: '70:08',
    page: 1,
    title: '苍月下的决意',
    type: '音乐·PV',
  },
  {
    time: '75:35',
    page: 1,
    title: '嘉宾祝福',
  },
  {
    time: '87:02',
    page: 1,
    title: 'Welcome Home',
    type: '音乐·PV',
  },
  {
    time: '92:09',
    page: 1,
    title: '完全凭依演奏会',
    type: '演奏',
    aid: '466062186',
    bvid: 'BV1DL411F7h7',
  },
  {
    time: '98:07',
    page: 1,
    title: '第 16 回东方 M1 漫才大奖赛 - 巫女巫女 Spark',
    type: '漫才',
  },
  {
    time: '106:14',
    page: 1,
    title: '再次来到紫樱树下',
    type: '音乐·PV',
  },
  {
    time: '109:35',
    page: 1,
    title: '月的另一侧',
    type: '演奏',
    aid: '978755047',
    bvid: 'BV1744y1W7Nh',
  },
  {
    time: '112:44',
    page: 1,
    title: '毛玉大战',
    type: 'Cosplay',
  },
  {
    time: '114:26',
    page: 1,
    title: '继续写下去, 直到最后',
    type: 'MAD',
  },
  {
    time: '118:07',
    page: 1,
    title: '东方热舞派对',
    type: '舞蹈',
  },
  {
    time: '123:57',
    page: 1,
    title: '尘世不变的悲观主义 ~ 心绮楼囃子',
    type: '演奏',
  },
  {
    time: '00:00',
    page: 2,
    title: '主持 3 - 灵梦, 文',
  },
  {
    time: '01:24',
    page: 2,
    title: 'Midnight glow-resurrection',
    type: '音乐·PV',
    aid: '893836342',
    bvid: 'BV1cP4y1P7Li',
  },
  {
    time: '06:14',
    page: 2,
    title: 'たぬすがぬ',
    type: '手书',
  },
  {
    time: '08:55',
    page: 2,
    title: '堇梦',
    type: '手书',
  },
  {
    time: '15:20',
    page: 2,
    title: '遇见',
    type: 'MMD',
  },
  {
    time: '19:16',
    page: 2,
    title: '卖烟花',
    type: '相声',
    aid: '636315065',
    bvid: 'BV19b4y1j7mK',
  },
  {
    time: '29:38',
    page: 2,
    title: '梦闲月谈',
    type: '音乐·PV',
  },
  {
    time: '33:56',
    page: 2,
    title: '东方绀珠传 LastBoss 组曲',
    type: '音乐·3D',
    aid: '636343941',
    bvid: 'BV1Ab4y177pm',
  },
  {
    time: '46:02',
    page: 2,
    title: '名侦探爱丽丝酱',
    type: '手书',
  },
  {
    time: '50:58',
    page: 2,
    title: '幻想乡の夏踊り',
    type: '舞蹈',
  },
  {
    time: '56:08',
    page: 2,
    title: '天 ~ Ancients',
    type: '音乐·PV',
  },
  {
    time: '61:04',
    page: 2,
    title: '最善的选择',
    type: 'Cosplay',
  },
  {
    time: '71:21',
    page: 2,
    title: '同人游戏宣传',
  },
  {
    time: '77:42',
    page: 2,
    title: '东方dots 战端再起',
    type: 'MMD',
  },
  {
    time: '84:42',
    page: 2,
    title: '源',
    type: '音乐·PV',
    aid: '508772972',
    bvid: 'BV1Hu411d7vL',
  },
  {
    time: '89:17',
    page: 2,
    title: 'Spelling Love',
    type: '手书',
  },
  {
    time: '93:24',
    page: 2,
    title: '神古战场',
    type: '演奏',
    aid: '211300439',
    bvid: 'BV1Ma411y7Ap',
  },
  {
    time: '97:09',
    page: 2,
    title: '馋死人',
    type: '音乐·PV',
    aid: '636279475',
    bvid: 'BV1kb4y1j7ip',
  },
  {
    time: '100:14',
    page: 2,
    title: '主持 4 - 阿求, 灵梦, 文, 妖梦',
  },
  {
    time: '102:07',
    page: 2,
    title: '谢幕「雁别平沙」',
    type: '音乐',
  },
]
